"""added project

Revision ID: 1e87f02e3305
Revises: b7148fc62a0b
Create Date: 2025-08-01 13:11:16.352642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e87f02e3305'
down_revision = 'b7148fc62a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.Text(length=5000), nullable=False),
    sa.Column('sections', sa.Text(length=5000), nullable=False),
    sa.Column('options', sa.Text(length=10000), nullable=False),
    sa.Column('last_edit_timestamp', sa.Float(), nullable=False),
    sa.Column('creation_timestamp', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
