"""added submissions

Revision ID: 7f237af6bce9
Revises: 1e87f02e3305
Create Date: 2025-08-01 20:42:25.789842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f237af6bce9'
down_revision = '1e87f02e3305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('submissions', sa.Text(length=10000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('creation_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_timestamp', sa.FLOAT(), nullable=False))

    op.drop_table('submissions')
    # ### end Alembic commands ###
